resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'github-nla-acme-nexus'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - 'src/Acme.BusinessApi.Libraries.Contracts/*'

jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    testProjectsPath: 'test/Contracts.Test/*.csproj'
    nugetProjectsPath: 'src/Acme.BusinessApi.Libraries.Contracts/*.csproj'
    publishVstsFeed: '7dea9355-6ff6-4e1e-9d36-7617d5d074ab'
